#!/bin/bash

set -u

# Always run from the script's own directory so relative paths
# work no matter where the user invokes it from.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Output zip lives in the user's home folder.
ZIP_FILE="$HOME/adflipr.zip"

# Files/folders that ship in the WordPress plugin distribution.
# Keep this allow-list in sync with the wordpress/ directory tree.
items_to_zip=(
    "adflipr.php"        # Plugin entry
    "uninstall.php"      # WP uninstall hook
    "readme.txt"         # WordPress.org plugin readme (required by WP)
    "README.md"          # General readme
    "includes"           # PHP classes loaded by adflipr.php
    "assets"             # Runtime JS (cart tracker, UTM tracker)
    "build"              # Compiled admin React app (wp-scripts build output)
)

# Patterns to exclude from the zip (OS junk, source maps, hidden cruft).
exclude_patterns=(
    "*.DS_Store"
    "*Thumbs.db"
    "*.map"
)

missing_items=()
for item in "${items_to_zip[@]}"; do
    if [ ! -e "$item" ]; then
        missing_items+=("$item")
    fi
done

echo "----------------------------------------"
echo "Creating plugin zip: $ZIP_FILE"
echo "Source dir:          $SCRIPT_DIR"
echo "----------------------------------------"

if [ ${#missing_items[@]} -gt 0 ]; then
    echo "Error: the following required files/folders are missing:"
    for item in "${missing_items[@]}"; do
        echo "  - $item"
    done
    echo "----------------------------------------"
    if [[ " ${missing_items[*]} " == *" build "* ]]; then
        echo "Hint: 'build/' is generated by wp-scripts. Run:"
        echo "  npm install && npm run build"
        echo "from $SCRIPT_DIR, then re-run this script."
        echo "----------------------------------------"
    fi
    exit 1
fi

# Remove any stale archive so we never merge into an old zip.
rm -f "$ZIP_FILE"

zip_args=(-r "$ZIP_FILE" "${items_to_zip[@]}")
for pattern in "${exclude_patterns[@]}"; do
    zip_args+=(-x "$pattern")
done

if zip "${zip_args[@]}" >/dev/null; then
    echo "Successfully created $ZIP_FILE"
    echo "----------------------------------------"
    echo "Contents:"
    zip -sf "$ZIP_FILE"
    echo "----------------------------------------"
else
    echo "----------------------------------------"
    echo "Failed to create zip file."
    echo "----------------------------------------"
    exit 1
fi
